# Generated by Django 5.1 on 2026-02-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_initial'),
        ('user', '0004_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='squads',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='user.squad'),
        ),
    ]
