# Generated by Django 5.1 on 2025-04-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FIREFIREFIGHTER', 'Firefirefighter'), ('TRUCK', 'Truck')], default='ADMIN', max_length=255),
        ),
    ]
