# Generated by Django 5.1 on 2025-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FIREFIGHTER', 'Firefighter'), ('TRUCK', 'Truck')], default='ADMIN', max_length=255),
        ),
    ]
