# Generated by Django 5.1 on 2025-04-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='squad',
        ),
        migrations.AddField(
            model_name='user',
            name='squad',
            field=models.ManyToManyField(blank=True, related_name='members', to='user.squad'),
        ),
    ]
